name: Deploy Site

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use NodeJS v12.18.3
              uses: actions/setup-node@v1
              with:
                  node-version: "12.18.3"

            - name: Generate (docs)
              run: npm install && npm run build

            - name: Delete files
              run: node scripts/build

            - name: Commit files
              run: |
                  git config --local user.email "bot@zyrouge.gq"
                  git config --local user.name "Beep Boop [bot]"
                  git add .
                  git commit -m "âœ¨ Generated Site"

            - name: Push changes to gh-pages
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  force: true
